[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
solc = "0.8.37"
optimizer = true
optimizer_runs = 999999
evm_version = "osaka"

[dependencies]
"forge-std" = { version = "1.16.2", git = "https://github.com/foundry-rs/forge-std.git", rev = "3e577a156f3ef021749e37be48a9804702a80b6e" }

[rpc_endpoints]
mainnet = "${ETH_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
